server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      enabled: true
    discovery:
      enabled: true
    gateway:
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/users/*/contents
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users,/users/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"