server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      enabled: true
    discovery:
      enabled: true
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/sessions,/sessions/*
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/users/*/posts,/posts/*,/users/*/posts/count
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users,/users/*
        - id: social-service
          uri: lb://social-service
          predicates:
            - Path=/likes/*,/posts/*/comments,/users/*/following,/users/*/followers,/comments/*,/posts/*/comments/*
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"