server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      enabled: true
    discovery:
      enabled: true
    gateway:
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/users/*/posts,/posts/*
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users,/users/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"